---
AWSTemplateFormatVersion: "2010-09-09"
Description: 'EKS Node Group definition.'

Parameters:

  ClusterName:
    Type: String
    Description: The EKS cluster name.

  EBSKeyName:
    Type: String
    Description: The KMS key to encrypt the node group worker EBS root volume

  NodeGroupName:
    Type: String
    Description: Unique identifier for the Node Group.

  NodeGroupRoleArn:
    Type: String
    Description: The ARN of the role for the nodegroup instances to assume.

  NodeInstanceType:
    Type: String
    Description: EC2 instance type for the node instances.

  NodeGroupDesiredCapacity:
    Type: Number
    Description: Desired capacity of Node Group ASG.

  NodeSubnets:
    Type: "List<AWS::EC2::Subnet::Id>"
    Description: The subnets where workers can be created.

Resources:
  LT:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        BlockDeviceMappings:
        -
          DeviceName: /dev/xvda
          Ebs:
            DeleteOnTermination: true
            Encrypted: true
            KmsKeyId: !Ref EBSKeyName
            VolumeType: gp2
        InstanceType: !Ref NodeInstanceType
  NodeGroup:
    Type: 'AWS::EKS::Nodegroup'
    Properties:
      NodegroupName: !Ref NodeGroupName
      ClusterName: !Ref ClusterName
      NodeRole: !Ref NodeGroupRoleArn
      LaunchTemplate: !Ref LT
      ScalingConfig:
        MinSize: 2
        DesiredSize: !Ref NodeGroupDesiredCapacity
        MaxSize: 5
      Subnets: !Ref NodeSubnets
